
"""
    Configuration
"""

# Réglage du PWM des moteurs
PWM_FREQUENCE = 50
SERVO_MIN = 160 # 202 # 187 min pour cam Y # 268 à 446 roues droit
SERVO_MAX = 485 # 404 # 533 MAX MAX

# Axe horizontal caméra
X_CAMERA_CHANNEL = 1
X_CAMERA_MIN = -90
X_CAMERA_MAX = 90
X_CAMERA_INITIAL = 0
X_CAMERA_CORRECTION = 0

# Axe vertical caméra
Y_CAMERA_CHANNEL = 11
Y_CAMERA_MIN = 50
Y_CAMERA_MAX = 80
Y_CAMERA_INITIAL = 60
Y_CAMERA_CORRECTION = 120  # 50 + 75

# Rotation des roues pour faire un virage
DIRECTION_CHANNEL = 13
DIRECTION_MIN = -45
DIRECTION_MAX = 45
DIRECTION_INITIAL = 0
DIRECTION_CORRECTION = -21

# Moteur 1
DC_MOTOR_L_CHANNEL = 7
MOTEUR_GAUCHE_PIN1 = 33
MOTEUR_GAUCHE_PIN2 = 37

# Moteur 2
DC_MOTOR_R_CHANNEL = 3
MOTEUR_DROIT_PIN1 = 31
MOTEUR_DROIT_PIN2 = 35
